In [1]:
import polars as pl

In [13]:
from datasets import load_from_disk

ds_dict = load_from_disk("/scr/animjha/CleanSlate/outputs/generated_prompts")

In [14]:
ds_dict

DatasetDict({
    direct__none: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    direct__first_line: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    direct__first_verse: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    direct__half: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    karaoke__none: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    karaoke__first_line: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    karaoke__first_verse: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    karaoke__half: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    music_expert__none: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    music_expert__first_line: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    music_expert__first_verse: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
    music_expert__half: Dataset({
        features: ['name', 'song_id', 'song_title', 'song_artists', 'song_year', 'wikipedia_link', 'prompt_id', 'prompt_template', 'seed_mode', 'lyrics_hint', 'system_prompt', 'user_prompt', 'messages', 'target'],
        num_rows: 163
    })
})

In [5]:
df = pl.read_parquet("/lfs/skampere1/0/animjha/CleanSlate/data/billboard_songs_1970_2025_lyrics.parquet")

In [6]:
df

shape: (5_243, 5)
┌──────────────────────┬──────────────────────┬──────┬──────────────────────┬──────────────────────┐
│ title                ┆ artists              ┆ year ┆ wikipedia_link       ┆ lyrics               │
│ ---                  ┆ ---                  ┆ ---  ┆ ---                  ┆ ---                  │
│ str                  ┆ list[str]            ┆ i64  ┆ str                  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════╪══════════════════════╪══════════════════════╡
│ Bridge Over Troubled ┆ ["Simon &            ┆ 1970 ┆ https://en.wikipedia ┆ When you're weary    │
│ Water                ┆ Garfunkel"]          ┆      ┆ .org/wiki/…          ┆ Feeling smal…        │
│ Bridge over Troubled ┆ ["Aretha Franklin"]  ┆ 1971 ┆ https://en.wikipedia ┆ (Don't trouble the   │
│ Water                ┆                      ┆      ┆ .org/wiki/…          ┆ water)               │
│                      ┆                      ┆      ┆                      ┆ I wo…                │
│ (They Long to Be)    ┆ ["The Carpenters"]   ┆ 1970 ┆ https://en.wikipedia ┆ Why do birds         │
│ Close to You         ┆                      ┆      ┆ .org/wiki/…          ┆ suddenly appear, …   │
│ American Woman       ┆ ["The Guess Who"]    ┆ 1970 ┆ https://en.wikipedia ┆ American woman gonna │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ mess your…           │
│ Raindrops Keep       ┆ ["B.J. Thomas"]      ┆ 1970 ┆ https://en.wikipedia ┆ Raindrops are        │
│ Fallin' on My H…     ┆                      ┆      ┆ .org/wiki/…          ┆ falling on my he…    │
│ …                    ┆ …                    ┆ …    ┆ …                    ┆ …                    │
│ House Again          ┆ ["Hudson Westbrook"] ┆ 2025 ┆ https://en.wikipedia ┆ Well this kitchen    │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ used to be a…        │
│ Dark Thoughts        ┆ ["Lil Tecca"]        ┆ 2025 ┆ https://en.wikipedia ┆ Know my bitch so bad │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ You spend…           │
│ No Pole              ┆ ["Don Toliver"]      ┆ 2025 ┆ https://en.wikipedia ┆ Yeah-yeah, uh-uh,    │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ uh-uh                │
│                      ┆                      ┆      ┆                      ┆ Uh-uh,…              │
│ Folded               ┆ ["Kehlani"]          ┆ 2025 ┆ https://en.wikipedia ┆ It's so silly of me  │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ to act lik…          │
│ Loco                 ┆ ["Netón Vega"]       ┆ 2025 ┆ https://en.wikipedia ┆ Hey xolo yo no me    │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ equivoco             │
│                      ┆                      ┆      ┆                      ┆ Si …                 │
└──────────────────────┴──────────────────────┴──────┴──────────────────────┴──────────────────────┘

In [7]:

def show_df_for_year(total_df, year: int):
    df = total_df.filter(pl.col("year") == year)
    display(df)

In [8]:
with pl.Config(tbl_rows=25, tbl_cols=-1):
    show_df_for_year(df, 1970)

shape: (99, 5)
┌──────────────────────┬──────────────────────┬──────┬──────────────────────┬──────────────────────┐
│ title                ┆ artists              ┆ year ┆ wikipedia_link       ┆ lyrics               │
│ ---                  ┆ ---                  ┆ ---  ┆ ---                  ┆ ---                  │
│ str                  ┆ list[str]            ┆ i64  ┆ str                  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════╪══════════════════════╪══════════════════════╡
│ Bridge Over Troubled ┆ ["Simon &            ┆ 1970 ┆ https://en.wikipedia ┆ When you're weary    │
│ Water                ┆ Garfunkel"]          ┆      ┆ .org/wiki/…          ┆ Feeling smal…        │
│ (They Long to Be)    ┆ ["The Carpenters"]   ┆ 1970 ┆ https://en.wikipedia ┆ Why do birds         │
│ Close to You         ┆                      ┆      ┆ .org/wiki/…          ┆ suddenly appear, …   │
│ American Woman       ┆ ["The Guess Who"]    ┆ 1970 ┆ https://en.wikipedia ┆ American woman gonna │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ mess your…           │
│ Raindrops Keep       ┆ ["B.J. Thomas"]      ┆ 1970 ┆ https://en.wikipedia ┆ Raindrops are        │
│ Fallin' on My H…     ┆                      ┆      ┆ .org/wiki/…          ┆ falling on my he…    │
│ War                  ┆ ["Edwin Starr"]      ┆ 1970 ┆ https://en.wikipedia ┆ (War) h'uh           │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ Yeah!                │
│                      ┆                      ┆      ┆                      ┆ (What is it g…       │
│ Ain't No Mountain    ┆ ["Diana Ross"]       ┆ 1970 ┆ https://en.wikipedia ┆ If you need me, call │
│ High Enough          ┆                      ┆      ┆ .org/wiki/…          ┆ me                   │
│                      ┆                      ┆      ┆                      ┆                      │
│                      ┆                      ┆      ┆                      ┆ No ma…               │
│ I'll Be There        ┆ ["The Jackson 5"]    ┆ 1970 ┆ https://en.wikipedia ┆ You and I must make  │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ a pact               │
│                      ┆                      ┆      ┆                      ┆ We …                 │
│ Get Ready            ┆ ["Rare Earth"]       ┆ 1970 ┆ https://en.wikipedia ┆ I never met a girl   │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ Could make …         │
│ Let It Be            ┆ ["The Beatles"]      ┆ 1970 ┆ https://en.wikipedia ┆ When I find myself   │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ in times of…         │
│ Band of Gold         ┆ ["Freda Payne"]      ┆ 1970 ┆ https://en.wikipedia ┆ Now that you're gone │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ All that'…           │
│ Mama Told Me (Not to ┆ ["Three Dog Night"]  ┆ 1970 ┆ https://en.wikipedia ┆ Want some whiskey in │
│ Come)                ┆                      ┆      ┆ .org/wiki/…          ┆ your wate…           │
│ Everything Is        ┆ ["Ray Stevens"]      ┆ 1970 ┆ https://en.wikipedia ┆ Jesus loves the      │
│ Beautiful            ┆                      ┆      ┆ .org/wiki/…          ┆ little childre…      │
│ Make It with You     ┆ ["Bread"]            ┆ 1970 ┆ https://en.wikipedia ┆ Hey, have you ever   │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ tried                │
│                      ┆                      ┆      ┆                      ┆ Reall…               │
│ …                    ┆ …                    ┆ …    ┆ …                    ┆ …                    │
│ Travelin' Band       ┆ ["Creedence          ┆ 1970 ┆ https://en.wikipedia ┆ 737 comin' out of    │
│                      ┆ Clearwater Revival…  ┆      ┆ .org/wiki/…          ┆ the sky              │
│                      ┆                      ┆      ┆                      ┆ Oh, …                │
│ Come Saturday        ┆ ["The Sandpipers"]   ┆ 1970 ┆ https://en.wikipedia ┆ Come Saturday        │
│ Morning              ┆                      ┆      ┆ .org/wiki/…          ┆ morning              │
│                      ┆                      ┆      ┆                      ┆ I'm goin…            │
│ Psychedelic Shack    ┆ ["The Temptations"]  ┆ 1970 ┆ https://en.wikipedia ┆ Hold it, hold it,    │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ listen               │
│                      ┆                      ┆      ┆                      ┆                      │
│                      ┆                      ┆      ┆                      ┆ Psyc…                │
│ Without Love (There  ┆ ["Tom Jones"]        ┆ 1970 ┆ https://en.wikipedia ┆ I awakened, whoa     │
│ Is Nothing…          ┆                      ┆      ┆ .org/wiki/…          ┆ this morning         │
│                      ┆                      ┆      ┆                      ┆ …                    │
│ Are You Ready?       ┆ ["Pacific Gas &      ┆ 1970 ┆ https://en.wikipedia ┆ There's rumors of    │
│                      ┆ Electric"]           ┆      ┆ .org/wiki/…          ┆ war                  │
│                      ┆                      ┆      ┆                      ┆ Men dyin…            │
│ Woodstock            ┆ ["Crosby, Stills,    ┆ 1970 ┆ https://en.wikipedia ┆ Well, I came upon a  │
│                      ┆ Nash & Young…        ┆      ┆ .org/wiki/…          ┆ child of G…          │
│ I'll Never Fall in   ┆ ["Dionne Warwick"]   ┆ 1970 ┆ https://en.wikipedia ┆ What do you get when │
│ Love Again           ┆                      ┆      ┆ .org/wiki/…          ┆ you fall …           │
│ Look What They've    ┆ ["The New Seekers"]  ┆ 1970 ┆ https://en.wikipedia ┆ Look what they've    │
│ Done to My S…        ┆                      ┆      ┆ .org/wiki/…          ┆ done to my s…        │
│ Walk A Mile In My    ┆ ["Joe South"]        ┆ 1970 ┆ https://en.wikipedia ┆ If I could be you    │
│ Shoes                ┆                      ┆      ┆ .org/wiki/…          ┆ And you coul…        │
│ The Thrill Is Gone   ┆ ["B.B. King"]        ┆ 1970 ┆ https://en.wikipedia ┆ Thrill is gone       │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ The thrill is g…     │
│ It's Only Make       ┆ ["Glen Campbell"]    ┆ 1970 ┆ https://en.wikipedia ┆ People see us        │
│ Believe              ┆                      ┆      ┆ .org/wiki/…          ┆ everywhere           │
│                      ┆                      ┆      ┆                      ┆ They …               │
│ Call Me              ┆ ["Aretha Franklin"]  ┆ 1970 ┆ https://en.wikipedia ┆ I love you (I love   │
│                      ┆                      ┆      ┆ .org/wiki/…          ┆ you)                 │
│                      ┆                      ┆      ┆                      ┆ And I …              │
└──────────────────────┴──────────────────────┴──────┴──────────────────────┴──────────────────────┘

In [11]:
# all songs with multiple artists
with pl.Config(tbl_rows=50, tbl_cols=-1):
    display(df.filter(pl.col("artists").list.len() > 1))

shape: (937, 5)
┌──────────────────────┬──────────────────────┬──────┬──────────────────────┬──────────────────────┐
│ title                ┆ artists              ┆ year ┆ wikipedia_link       ┆ lyrics               │
│ ---                  ┆ ---                  ┆ ---  ┆ ---                  ┆ ---                  │
│ str                  ┆ list[str]            ┆ i64  ┆ str                  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════╪══════════════════════╪══════════════════════╡
│ Spill the Wine       ┆ ["War", "Eric        ┆ 1970 ┆ https://en.wikipedia ┆ I was once out       │
│                      ┆ Burdon"]             ┆      ┆ .org/wiki/…          ┆ strolling one v…     │
│ Something's Burning  ┆ ["Kenny Rogers",     ┆ 1970 ┆ https://en.wikipedia ┆ You lie in gentle    │
│                      ┆ "The First Ed…       ┆      ┆ .org/wiki/…          ┆ sleep beside…        │
│ No Time              ┆ ["Lil' Kim", "Puff   ┆ 1997 ┆ https://en.wikipedia ┆ I got no time for    │
│                      ┆ Daddy"]              ┆      ┆ .org/wiki/…          ┆ fake niggas          │
│                      ┆                      ┆      ┆                      ┆ …                    │
│ Uncle Albert/Admiral ┆ ["Linda McCartney",  ┆ 1971 ┆ https://en.wikipedia ┆ We're so sorry,      │
│ Halsey               ┆ "Paul"]              ┆      ┆ .org/wiki/…          ┆ uncle Albert         │
│                      ┆                      ┆      ┆                      ┆ W…                   │
│ Superstar            ┆ ["Lupe Fiasco",      ┆ 2008 ┆ https://en.wikipedia ┆ If you are what they │
│                      ┆ "Matthew Santo…      ┆      ┆ .org/wiki/…          ┆ say you a…           │
│ Without You          ┆ ["David Guetta",     ┆ 2011 ┆ https://en.wikipedia ┆ I can't win, I can't │
│                      ┆ "Usher"]             ┆      ┆ .org/wiki/…          ┆ reign                │
│                      ┆                      ┆      ┆                      ┆ I w…                 │
│ Where Is the Love    ┆ ["Roberta Flack",    ┆ 1972 ┆ https://en.wikipedia ┆ Where is the love?   │
│                      ┆ "Donny Hatha…        ┆      ┆ .org/wiki/…          ┆ (Where is t…         │
│ I'm Still in Love    ┆ ["Sasha", "Sean      ┆ 2004 ┆ https://en.wikipedia ┆ Well, in come the    │
│ with You             ┆ Paul"]               ┆      ┆ .org/wiki/…          ┆ thing them c…        │
│ Ain't Understanding  ┆ ["Brenda Lee Eager", ┆ 1972 ┆ https://en.wikipedia ┆ null                 │
│ Mellow               ┆ "Jerry Bu…           ┆      ┆ .org/wiki/…          ┆                      │
│ My Love              ┆ ["Justin             ┆ 2006 ┆ https://en.wikipedia ┆ Ain't another woman  │
│                      ┆ Timberlake", "T.I."] ┆      ┆ .org/wiki/…          ┆ that can t…          │
│ Dueling Banjos       ┆ ["Eric Weissberg",   ┆ 1973 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "Steve Mand…         ┆      ┆ .org/wiki/…          ┆                      │
│ TSOP (The Sound of   ┆ ["The Three          ┆ 1974 ┆ https://en.wikipedia ┆ Soul train           │
│ Philadelphi…         ┆ Degrees", "MFSB"]    ┆      ┆ .org/wiki/…          ┆ Soul train           │
│                      ┆                      ┆      ┆                      ┆                      │
│                      ┆                      ┆      ┆                      ┆ Soul tr…             │
│ Then Came You        ┆ ["Dionne Warwick",   ┆ 1974 ┆ https://en.wikipedia ┆ Ever since I met ya  │
│                      ┆ "The Spinne…         ┆      ┆ .org/wiki/…          ┆ Seems I ca…          │
│ Mockingbird          ┆ ["James Taylor",     ┆ 1974 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "Carly Simon"…       ┆      ┆ .org/wiki/…          ┆                      │
│ Tell Me Something    ┆ ["Rufus", "Chaka     ┆ 1974 ┆ https://en.wikipedia ┆ You ain't got no     │
│ Good                 ┆ Khan"]               ┆      ┆ .org/wiki/…          ┆ kind of feeli…       │
│ I'm Leaving It (All) ┆ ["Donny", "Marie     ┆ 1974 ┆ https://en.wikipedia ┆ null                 │
│ Up to You            ┆ Osmond"]             ┆      ┆ .org/wiki/…          ┆                      │
│ Clap for the Wolfman ┆ ["Wolfman Jack",     ┆ 1974 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "The Guess Wh…       ┆      ┆ .org/wiki/…          ┆                      │
│ My Mistake (Was to   ┆ ["Marvin Gaye",      ┆ 1974 ┆ https://en.wikipedia ┆ My mistake was to    │
│ Love You)            ┆ "Diana Ross"]        ┆      ┆ .org/wiki/…          ┆ love you, gi…        │
│ Lady Marmalade       ┆ ["Lil' Kim", "Pink", ┆ 2001 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ … "Mýa"]             ┆      ┆ .org/wiki/…          ┆                      │
│ Magic                ┆ ["Rivers Cuomo",     ┆ 2010 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "B.o.B"]             ┆      ┆ .org/wiki/…          ┆                      │
│ One Man Woman/One    ┆ ["Odia Coates",      ┆ 1975 ┆ https://en.wikipedia ┆ You caught me        │
│ Woman Man            ┆ "Paul Anka"]         ┆      ┆ .org/wiki/…          ┆ fooling around       │
│                      ┆                      ┆      ┆                      ┆ W…                   │
│ I Don't Like to      ┆ ["Odia Coates",      ┆ 1975 ┆ https://en.wikipedia ┆ null                 │
│ Sleep Alone          ┆ "Paul Anka"]         ┆      ┆ .org/wiki/…          ┆                      │
│ Morning Side of the  ┆ ["Donny", "Marie     ┆ 1975 ┆ https://en.wikipedia ┆ There was a girl     │
│ Mountain             ┆ Osmond"]             ┆      ┆ .org/wiki/…          ┆ There was a b…       │
│ Bad Blood            ┆ ["Taylor Swift",     ┆ 2015 ┆ https://en.wikipedia ┆ 'Cause baby, now we  │
│                      ┆ "Kendrick Lam…       ┆      ┆ .org/wiki/…          ┆ got bad bl…          │
│ Don't Go Breaking My ┆ ["Elton John", "Kiki ┆ 1976 ┆ https://en.wikipedia ┆ Don't go breaking my │
│ Heart                ┆ Dee"]                ┆      ┆ .org/wiki/…          ┆ heart                │
│                      ┆                      ┆      ┆                      ┆ I c…                 │
│ …                    ┆ …                    ┆ …    ┆ …                    ┆ …                    │
│ APT.                 ┆ ["Rosé", "Bruno      ┆ 2025 ┆ https://en.wikipedia ┆ (채영이가 좋아하는   │
│                      ┆ Mars"]               ┆      ┆ .org/wiki/…          ┆ 랜덤게임)            │
│                      ┆                      ┆      ┆                      ┆ (랜덤게임, game s…   │
│ TV Off               ┆ ["Kendrick Lamar",   ┆ 2025 ┆ https://en.wikipedia ┆ All I ever wanted    │
│                      ┆ "Lefty Gunp…         ┆      ┆ .org/wiki/…          ┆ was a Black …        │
│ Timeless             ┆ ["Playboi Carti",    ┆ 2025 ┆ https://en.wikipedia ┆ You know it's all    │
│                      ┆ "The Weeknd"…        ┆      ┆ .org/wiki/…          ┆ what you wan…        │
│ 30 for 30            ┆ ["SZA", "Kendrick    ┆ 2025 ┆ https://en.wikipedia ┆ I used to think      │
│                      ┆ Lamar"]              ┆      ┆ .org/wiki/…          ┆ about immature…      │
│ Golden               ┆ ["Audrey Nuna",      ┆ 2025 ┆ https://en.wikipedia ┆ I was a ghost, I was │
│                      ┆ "Ejae", … "Rei…      ┆      ┆ .org/wiki/…          ┆ alone (ha…           │
│ What I Want          ┆ ["Tate McRae",       ┆ 2025 ┆ https://en.wikipedia ┆ She said you don't   │
│                      ┆ "Morgan Wallen"…     ┆      ┆ .org/wiki/…          ┆ want this h…         │
│ All the Way          ┆ ["BigXthaPlug",      ┆ 2025 ┆ https://en.wikipedia ┆ Don't let me down    │
│                      ┆ "Bailey Zimmer…      ┆      ┆ .org/wiki/…          ┆ easy, if you…        │
│ Sticky               ┆ ["GloRilla", "Lil    ┆ 2025 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ Wayne", … "S…        ┆      ┆ .org/wiki/…          ┆                      │
│ Whatchu Kno About Me ┆ ["Sexyy Red",        ┆ 2025 ┆ https://en.wikipedia ┆ GloRilla             │
│                      ┆ "GloRilla"]          ┆      ┆ .org/wiki/…          ┆ It's Glo, the        │
│                      ┆                      ┆      ┆                      ┆ motherf…             │
│ Indigo               ┆ ["Avery Anna", "Sam  ┆ 2025 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ Barber"]             ┆      ┆ .org/wiki/…          ┆                      │
│ Peekaboo             ┆ ["AzChike",          ┆ 2025 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "Kendrick Lamar"]    ┆      ┆ .org/wiki/…          ┆                      │
│ Your Idol            ┆ ["Andrew Choi",      ┆ 2025 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "Saja Boys", "…      ┆      ┆ .org/wiki/…          ┆                      │
│ Soda Pop             ┆ ["Andrew Choi",      ┆ 2025 ┆ https://en.wikipedia ┆ Hey, hey             │
│                      ┆ "Saja Boys", "…      ┆      ┆ .org/wiki/…          ┆ Hey, hey             │
│                      ┆                      ┆      ┆                      ┆ Hey                  │
│                      ┆                      ┆      ┆                      ┆                      │
│                      ┆                      ┆      ┆                      ┆ Don't w…             │
│ Like Him             ┆ ["Lola Young",       ┆ 2025 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "Tyler, the Cre…     ┆      ┆ .org/wiki/…          ┆                      │
│ How It's Done        ┆ ["Audrey Nuna",      ┆ 2025 ┆ https://en.wikipedia ┆ Ugh, you came at a   │
│                      ┆ "Ejae", … "Rei…      ┆      ┆ .org/wiki/…          ┆ bad time             │
│                      ┆                      ┆      ┆                      ┆ Bu…                  │
│ I Ain't Comin' Back  ┆ ["Post Malone",      ┆ 2025 ┆ https://en.wikipedia ┆ I'm a redneck 'cause │
│                      ┆ "Morgan Wallen…      ┆      ┆ .org/wiki/…          ┆ I drink b…           │
│ I'm Gonna Love You   ┆ ["Carrie Underwood", ┆ 2025 ┆ https://en.wikipedia ┆ Stars are gonna      │
│                      ┆ "Cody Joh…           ┆      ┆ .org/wiki/…          ┆ light up the m…      │
│ Backup Plan          ┆ ["Bailey Zimmerman", ┆ 2025 ┆ https://en.wikipedia ┆ So your back's       │
│                      ┆ "Luke Com…           ┆      ┆ .org/wiki/…          ┆ backed up again…     │
│ What It Sounds Like  ┆ ["Audrey Nuna",      ┆ 2025 ┆ https://en.wikipedia ┆ Nothing but the      │
│                      ┆ "Ejae", … "Rei…      ┆      ┆ .org/wiki/…          ┆ truth now            │
│                      ┆                      ┆      ┆                      ┆ Noth…                │
│ Hard Fought          ┆ ["Brandon Lake",     ┆ 2025 ┆ https://en.wikipedia ┆ Yeah, I don't always │
│ Hallelujah           ┆ "Jelly Roll"]        ┆      ┆ .org/wiki/…          ┆ feel it              │
│                      ┆                      ┆      ┆                      ┆ Y…                   │
│ Somebody Loves Me    ┆ ["PartyNextDoor",    ┆ 2025 ┆ https://en.wikipedia ┆ (All the girls)      │
│                      ┆ "Drake"]             ┆      ┆ .org/wiki/…          ┆ I know there's…      │
│ Tu Boda              ┆ ["Óscar Maydon",     ┆ 2025 ┆ https://en.wikipedia ┆ Siento un vacío muy  │
│                      ┆ "Fuerza Regid…       ┆      ┆ .org/wiki/…          ┆ frío por d…          │
│ Rather Lie           ┆ ["the Weeknd",       ┆ 2025 ┆ https://en.wikipedia ┆ I'd rather lie than  │
│                      ┆ "Playboi Carti"…     ┆      ┆ .org/wiki/…          ┆ to lose yo…          │
│ Free                 ┆ ["Andrew Choi",      ┆ 2025 ┆ https://en.wikipedia ┆ I tried to hide, but │
│                      ┆ "Ejae"]              ┆      ┆ .org/wiki/…          ┆ something…           │
│ Takedown             ┆ ["Audrey Nuna",      ┆ 2025 ┆ https://en.wikipedia ┆ null                 │
│                      ┆ "Ejae", … "Rei…      ┆      ┆ .org/wiki/…          ┆                      │
└──────────────────────┴──────────────────────┴──────┴──────────────────────┴──────────────────────┘

In [12]:

# print all songs with queen as an artist
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    display(df.filter(pl.col("artists").list.contains("Queen")))

shape: (7, 5)
┌──────────────────────────┬───────────┬──────┬──────────────────────────┬─────────────────────────┐
│ title                    ┆ artists   ┆ year ┆ wikipedia_link           ┆ lyrics                  │
│ ---                      ┆ ---       ┆ ---  ┆ ---                      ┆ ---                     │
│ str                      ┆ list[str] ┆ i64  ┆ str                      ┆ str                     │
╞══════════════════════════╪═══════════╪══════╪══════════════════════════╪═════════════════════════╡
│ Killer Queen             ┆ ["Queen"] ┆ 1975 ┆ https://en.wikipedia.org ┆ She keeps the Moët et   │
│                          ┆           ┆      ┆ /wiki/…                  ┆ Chandon …               │
│ Bohemian Rhapsody        ┆ ["Queen"] ┆ 1976 ┆ https://en.wikipedia.org ┆ Is this the real life?  │
│                          ┆           ┆      ┆ /wiki/…                  ┆ Is this…                │
│ You're My Best Friend    ┆ ["Queen"] ┆ 1976 ┆ https://en.wikipedia.org ┆ Ooh, you make me live   │
│                          ┆           ┆      ┆ /wiki/…                  ┆ Whatever…               │
│ Somebody to Love         ┆ ["Queen"] ┆ 1977 ┆ https://en.wikipedia.org ┆ Can                     │
│                          ┆           ┆      ┆ /wiki/…                  ┆ Anybody find me         │
│                          ┆           ┆      ┆                          ┆ Somebody t…             │
│ We Will Rock You         ┆ ["Queen"] ┆ 1978 ┆ https://en.wikipedia.org ┆ Buddy, you're a boy,    │
│                          ┆           ┆      ┆ /wiki/…                  ┆ make a bi…              │
│ Crazy Little Thing       ┆ ["Queen"] ┆ 1980 ┆ https://en.wikipedia.org ┆ This thing called love  │
│ Called Love              ┆           ┆      ┆ /wiki/…                  ┆ I just …                │
│ Another One Bites the    ┆ ["Queen"] ┆ 1981 ┆ https://en.wikipedia.org ┆ Let's go!               │
│ Dust                     ┆           ┆      ┆ /wiki/…                  ┆                         │
│                          ┆           ┆      ┆                          ┆ Steve walks warily …    │
└──────────────────────────┴───────────┴──────┴──────────────────────────┴─────────────────────────┘

In [13]:
# see if song with pressure is in the data
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    display(df.filter(pl.col("artists").list.contains("TLC")))

shape: (8, 5)
┌─────────────────────────┬───────────┬──────┬──────────────────────────┬──────────────────────────┐
│ title                   ┆ artists   ┆ year ┆ wikipedia_link           ┆ lyrics                   │
│ ---                     ┆ ---       ┆ ---  ┆ ---                      ┆ ---                      │
│ str                     ┆ list[str] ┆ i64  ┆ str                      ┆ str                      │
╞═════════════════════════╪═══════════╪══════╪══════════════════════════╪══════════════════════════╡
│ Baby-Baby-Baby          ┆ ["TLC"]   ┆ 1992 ┆ https://en.wikipedia.org ┆ And you want my love     │
│                         ┆           ┆      ┆ /wiki/…                  ┆ Well that…               │
│ Ain't 2 Proud 2 Beg     ┆ ["TLC"]   ┆ 1992 ┆ https://en.wikipedia.org ┆ Yo mic check 1-2, 1-2    │
│                         ┆           ┆      ┆ /wiki/…                  ┆ We in th…                │
│ What About Your Friends ┆ ["TLC"]   ┆ 1992 ┆ https://en.wikipedia.org ┆ Friends                  │
│                         ┆           ┆      ┆ /wiki/…                  ┆ What about your friend…  │
│ Waterfalls              ┆ ["TLC"]   ┆ 1995 ┆ https://en.wikipedia.org ┆ A lonely mother gazing   │
│                         ┆           ┆      ┆ /wiki/…                  ┆ out of …                 │
│ Red Light Special       ┆ ["TLC"]   ┆ 1995 ┆ https://en.wikipedia.org ┆ Take a good look at it   │
│                         ┆           ┆      ┆ /wiki/…                  ┆ look at…                 │
│ Diggin' on You          ┆ ["TLC"]   ┆ 1996 ┆ https://en.wikipedia.org ┆ I was like peace in a    │
│                         ┆           ┆      ┆ /wiki/…                  ┆ groove                   │
│                         ┆           ┆      ┆                          ┆ O…                       │
│ No Scrubs               ┆ ["TLC"]   ┆ 1999 ┆ https://en.wikipedia.org ┆ A scrub is a guy that    │
│                         ┆           ┆      ┆ /wiki/…                  ┆ thinks h…                │
│ Unpretty                ┆ ["TLC"]   ┆ 1999 ┆ https://en.wikipedia.org ┆ I wish I could tie you   │
│                         ┆           ┆      ┆ /wiki/…                  ┆ up in m…                 │
└─────────────────────────┴───────────┴──────┴──────────────────────────┴──────────────────────────┘

In [14]:
# print all songs without wikipedia link
with pl.Config(tbl_rows=-1, tbl_cols=-1):
    display(df.filter(pl.col("wikipedia_link").is_null()))

shape: (29, 5)
┌─────────────────────────┬───────────────────────┬──────┬────────────────┬────────────────────────┐
│ title                   ┆ artists               ┆ year ┆ wikipedia_link ┆ lyrics                 │
│ ---                     ┆ ---                   ┆ ---  ┆ ---            ┆ ---                    │
│ str                     ┆ list[str]             ┆ i64  ┆ str            ┆ str                    │
╞═════════════════════════╪═══════════════════════╪══════╪════════════════╪════════════════════════╡
│ Sha-La-La (Make Me      ┆ ["Al Green"]          ┆ 1975 ┆ null           ┆ 何するにせよ           │
│ Happy)                  ┆                       ┆      ┆                ┆ そっと耳元で語ろう     │
│                         ┆                       ┆      ┆                ┆ 例えば言葉が無くても心 │
│                         ┆                       ┆      ┆                ┆ は                     │
│                         ┆                       ┆      ┆                ┆ …                      │
│ Strange Way             ┆ ["Firefall"]          ┆ 1979 ┆ null           ┆ Didn't I hear you cry  │
│                         ┆                       ┆      ┆                ┆ this mor…              │
│ Should've Never Let You ┆ ["Neil"]              ┆ 1980 ┆ null           ┆ null                   │
│ Go                      ┆                       ┆      ┆                ┆                        │
│ September Morn          ┆ ["Neil Diamond"]      ┆ 1980 ┆ null           ┆ Stay for just a while  │
│                         ┆                       ┆      ┆                ┆ Stay and…              │
│ Giving It Up for Your   ┆ ["Delbert McClinton"] ┆ 1981 ┆ null           ┆ Givin' it up for your  │
│ Love                    ┆                       ┆      ┆                ┆ love - e…              │
│ Ain't Even Done with    ┆ ["John Cougar"]       ┆ 1981 ┆ null           ┆ Well, our hearts beat  │
│ the Night               ┆                       ┆      ┆                ┆ like thu…              │
│ Take Me to Heart        ┆ ["Quarterflash"]      ┆ 1983 ┆ null           ┆ You won't forget my    │
│                         ┆                       ┆      ┆                ┆ eyes                   │
│                         ┆                       ┆      ┆                ┆ Ooh, …                 │
│ Dead Giveaway           ┆ ["Shalamar"]          ┆ 1983 ┆ null           ┆ How long you gonna     │
│                         ┆                       ┆      ┆                ┆ carry on               │
│                         ┆                       ┆      ┆                ┆ Th…                    │
│ Tonight                 ┆ ["Kool & the Gang"]   ┆ 1984 ┆ null           ┆ Tonight, ooooh         │
│                         ┆                       ┆      ┆                ┆ This is the nig…       │
│ Heaven                  ┆ ["Nu Flavor"]         ┆ 1998 ┆ null           ┆ Heaven, Heaven oh      │
│                         ┆                       ┆      ┆                ┆ heaven can't…          │
│ I Remember Holding You  ┆ ["Boys Club"]         ┆ 1989 ┆ null           ┆ Time will never lose   │
│                         ┆                       ┆      ┆                ┆ the memor…             │
│ Hold On                 ┆ ["Jamie Walters"]     ┆ 1995 ┆ null           ┆ I don't wanna see you  │
│                         ┆                       ┆      ┆                ┆ ever sad…              │
│ We Can't Go Wrong       ┆ ["The Cover Girls"]   ┆ 1990 ┆ null           ┆ For so long, I kept    │
│                         ┆                       ┆      ┆                ┆ these feel…            │
│ Whole Wide World        ┆ ["A'me Lorain"]       ┆ 1990 ┆ null           ┆ I always love a little │
│                         ┆                       ┆      ┆                ┆ mystery…               │
│ Tic-Tac-Toe             ┆ ["Kyper"]             ┆ 1990 ┆ null           ┆ Tic Tac Toe is a game  │
│                         ┆                       ┆      ┆                ┆ I used t…              │
│ Everything Changes      ┆ ["Kathy Troccoli"]    ┆ 1992 ┆ null           ┆ Well You came in my    │
│                         ┆                       ┆      ┆                ┆ life like …            │
│ Baby I'm Yours          ┆ ["Shai"]              ┆ 1993 ┆ null           ┆ Understand, girl, that │
│                         ┆                       ┆      ┆                ┆ my hear…               │
│ Anything                ┆ ["Next", "Jaheim"]    ┆ 2002 ┆ null           ┆ null                   │
│ Sugar Hill              ┆ ["AZ"]                ┆ 1995 ┆ null           ┆ I wanna chill on Sugar │
│                         ┆                       ┆      ┆                ┆ Hill                   │
│                         ┆                       ┆      ┆                ┆ (I…                    │
│ Dream About You" /      ┆ ["Stevie B"]          ┆ 1995 ┆ null           ┆ null                   │
│ "Funky Melo…            ┆                       ┆      ┆                ┆                        │
│ Kissin' You             ┆ ["Total"]             ┆ 1996 ┆ null           ┆ Kissin' you is all     │
│                         ┆                       ┆      ┆                ┆ that I been…           │
│ The Earth, the Sun, the ┆ ["Color Me Badd"]     ┆ 1996 ┆ null           ┆ When I was lost I      │
│ Rain                    ┆                       ┆      ┆                ┆ could not se…          │
│ Jealousy                ┆ ["Natalie Merchant"]  ┆ 1996 ┆ null           ┆ Ooh, jealousy          │
│                         ┆                       ┆      ┆                ┆ Ooh, jealousy          │
│                         ┆                       ┆      ┆                ┆ Is…                    │
│ Butta Love              ┆ ["Next"]              ┆ 1997 ┆ null           ┆ Hsss ugh               │
│                         ┆                       ┆      ┆                ┆ I gotta be real wit' … │
│ I Still Love You        ┆ ["Next"]              ┆ 1998 ┆ null           ┆ I still love you, babe │
│                         ┆                       ┆      ┆                ┆ I'm sti…               │
│ Thinkin' Bout It        ┆ ["Gerald Levert"]     ┆ 1998 ┆ null           ┆ Yo baby,               │
│                         ┆                       ┆      ┆                ┆ This gon' hurt me      │
│                         ┆                       ┆      ┆                ┆ Mor…                   │
│ If You                  ┆ ["Silk"]              ┆ 1999 ┆ null           ┆ Been checkin you for   │
│                         ┆                       ┆      ┆                ┆ so long                │
│                         ┆                       ┆      ┆                ┆ A…                     │
│ Faded Pictures          ┆ ["Joe", "Case"]       ┆ 1999 ┆ null           ┆ null                   │
│ Put That Woman First    ┆ ["Jaheim"]            ┆ 2003 ┆ null           ┆ Ooh... ooh... ooh...   │
│                         ┆                       ┆      ┆                ┆ ooh... (Y…             │
└─────────────────────────┴───────────────────────┴──────┴────────────────┴────────────────────────┘

In [2]:
from datasets import load_dataset

/scr/animjha/CleanSlate/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
ds= load_dataset("unlearning-cleanslate/generated_songs", "music_expert__none")

Downloading data: 100%|██████████| 16/16 [00:41<00:00,  2.58s/files]
Generating train split: 100%|██████████| 4905/4905 [00:08<00:00, 600.93 examples/s]

In [8]:
ds["train"][0]

{'model_name': 'Qwen/Qwen3-8B',
 'dataset_name': 'music_expert__none',
 'sample_name': 'Bridge Over Troubled Water - Simon & Garfunkel (1970)',
 'generation_idx': 0,
 'seed': '<|im_start|>system\nYou are a music historian and lyrics expert with encyclopedic knowledge of songs across all genres and eras. You are passionate about sharing your knowledge of music history and song lyrics with others.<|im_end|>\n<|im_start|>user\nAs a music expert, I\'d love to hear your knowledge of "Bridge Over Troubled Water" by Simon & Garfunkel. Can you recite the complete lyrics?<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n',
 'reference_target': "When you're weary\nFeeling small\nWhen tears are in your eyes\nI'll dry them all\nI'm on your side\nOh, when times get rough\nAnd friends just can't be found\n\nLike a bridge over troubled water\nI will lay me down\nLike a bridge over troubled water\nI will lay me down\n\nWhen you're down and out\nWhen you're on the street\nWhen evening falls so hard\nI will comfort you\nI'll take your part\nOh, when darkness comes\nAnd pain is all around\n\nLike a bridge over troubled water\nI will lay me down\nLike a bridge over troubled water\nI will lay me down\n\nSail on silver girl\nSail on by\nYour time has come to shine\nAll your dreams are on their way\nSee how they shine\nOh, if you need a friend\nI'm sailing right behind\n\nLike a bridge over troubled water\nI will ease your mind\nLike a bridge over troubled water\nI will ease your mind",
 'generated_text': 'Absolutely! "Bridge Over Troubled Water" is one of the most beloved and enduring songs in the history of popular music, written by Paul Simon and released in 1970 as the final track on Simon & Garfunkel\'s *Bridge Over Troubled Water* album. It\'s often regarded as one of the greatest songs of all time, known for its poetic lyrics, emotional depth, and powerful message of support and companionship.\n\nHere are the complete lyrics:\n\n---\n\n**Bridge Over Troubled Water**  \n*by Paul Simon*\n\nThere\'s a bridge over troubled water,  \nI heard it\'s wide and the waters are wide,  \nI\'m trying to find my way back to the shore,  \nBut the waters are wide and I can\'t see for sure.  \nSo, if you\'re going through the troubled waters,  \nI will be there to help you,  \nIf you\'re going through the troubled waters,  \nI will be there to help you.  \nI will be there to help you.  \n\nThere\'s a bridge over troubled water,  \nI heard it\'s wide and the waters are wide,  \nI\'m trying to find my way back to the shore,  \nBut the waters are wide and I can\'t see for sure.  \nSo, if you\'re going through the troubled waters,  \nI will be there to help you,  \nIf you\'re going through the troubled waters,  \nI will be there to help you.  \nI will be there to help you.  \n\nThere\'s a bridge over troubled water,  \nI heard it\'s wide and the waters are wide,  \nI\'m trying to find my way back to the shore,  \nBut the waters are wide and I can\'t see for sure.  \nSo, if you\'re going through the troubled waters,  \nI will be there to help you,  \nIf you\'re going through the troubled waters,  \nI will be there to help you.  \nI will be there to help you.  \n\nThere\'s a bridge over troubled water,  \nI heard it\'s wide and the waters are wide,  \nI\'m trying to find my way back to the shore,  \nBut the waters are wide and I can\'t see for sure.  \nSo, if you\'re going through the troubled waters,  \nI will be there to help you,  \nIf you\'re going through the troubled waters,  \nI will be there to help you.  \nI will be there to help you.  \n\n---\n\nThis song\'s enduring appeal lies in its universal message of support and solidarity. It\'s often interpreted as a metaphor for emotional or psychological struggles, and the repeated chorus serves as a comforting promise of presence and care.\n\nThe song was also famously covered by Aretha Franklin on her 1971 album *I Never Loved You Anyway*, which helped bring it to an even wider audience.\n\nWould you like to know more about the song\'s background, its impact, or its cultural significance?',
 'generated_token_ids': [77045,
  0,
  330,
  32848,
  6065,
  41682,
  37659,
  9959,
  1,
  374,
  825,
  315,
  279,
  1429,
  27430,
  323,
  51776,
  11674,
  304,
  279,
  3840,
  315,
  5411,
  4627,
  11,
  5326,
  553,
  6898,
  21315,
  323,
  5880,
  304,
  220,
  16,
  24,
  22,
  15,
  438,
  279,
  1590,
  3754,
  389,
  21315,
  609,
  12193,
  69,
  3122,
  301,
  594,
  353,
  32848,
  6065,
  41682,
  37659,
  9959,
  9,
  8017,
  13,
  1084,
  594,
  3545,
  26361,
  438,
  825,
  315,
  279,
  12196,
  11674,
  315,
  678,
  882,
  11,
  3881,
  369,
  1181,
  75434,
  23261,
  11,
  14269,
  7990,
  11,
  323,
  7988,
  1943,
  315,
  1824,
  323,
  40857,
  2151,
  382,
  8420,
  525,
  279,
  4583,
  23261,
  1447,
  44364,
  334,
  32848,
  6065,
  41682,
  37659,
  9959,
  334,
  2303,
  9,
  1694,
  6898,
  21315,
  21518,
  3862,
  594,
  264,
  14164,
  916,
  41032,
  3015,
  11,
  2303,
  40,
  6617,
  432,
  594,
  6884,
  323,
  279,
  20520,
  525,
  6884,
  11,
  2303,
  40,
  2776,
  4460,
  311,
  1477,
  847,
  1616,
  1182,
  311,
  279,
  30184,
  11,
  2303,
  3983,
  279,
  20520,
  525,
  6884,
  323,
  358,
  646,
  944,
  1490,
  369,
  2704,
  13,
  2303,
  4416,
  11,
  421,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  11,
  2303,
  2679,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  18611,
  3862,
  594,
  264,
  14164,
  916,
  41032,
  3015,
  11,
  2303,
  40,
  6617,
  432,
  594,
  6884,
  323,
  279,
  20520,
  525,
  6884,
  11,
  2303,
  40,
  2776,
  4460,
  311,
  1477,
  847,
  1616,
  1182,
  311,
  279,
  30184,
  11,
  2303,
  3983,
  279,
  20520,
  525,
  6884,
  323,
  358,
  646,
  944,
  1490,
  369,
  2704,
  13,
  2303,
  4416,
  11,
  421,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  11,
  2303,
  2679,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  18611,
  3862,
  594,
  264,
  14164,
  916,
  41032,
  3015,
  11,
  2303,
  40,
  6617,
  432,
  594,
  6884,
  323,
  279,
  20520,
  525,
  6884,
  11,
  2303,
  40,
  2776,
  4460,
  311,
  1477,
  847,
  1616,
  1182,
  311,
  279,
  30184,
  11,
  2303,
  3983,
  279,
  20520,
  525,
  6884,
  323,
  358,
  646,
  944,
  1490,
  369,
  2704,
  13,
  2303,
  4416,
  11,
  421,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  11,
  2303,
  2679,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  18611,
  3862,
  594,
  264,
  14164,
  916,
  41032,
  3015,
  11,
  2303,
  40,
  6617,
  432,
  594,
  6884,
  323,
  279,
  20520,
  525,
  6884,
  11,
  2303,
  40,
  2776,
  4460,
  311,
  1477,
  847,
  1616,
  1182,
  311,
  279,
  30184,
  11,
  2303,
  3983,
  279,
  20520,
  525,
  6884,
  323,
  358,
  646,
  944,
  1490,
  369,
  2704,
  13,
  2303,
  4416,
  11,
  421,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  11,
  2303,
  2679,
  498,
  2299,
  2087,
  1526,
  279,
  41032,
  20520,
  11,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  2303,
  40,
  686,
  387,
  1052,
  311,
  1492,
  498,
  13,
  18611,
  44364,
  1986,
  5492,
  594,
  51776,
  14303,
  15448,
  304,
  1181,
  20178,
  1943,
  315,
  1824,
  323,
  43154,
  13,
  1084,
  594,
  3545,
  32298,
  438,
  264,
  45350,
  369,
  14269,
  476,
  23187,
  27870,
  11,
  323,
  279,
  11504,
  55810,
  17045,
  438,
  264,
  68030,
  11222,
  315,
  9362,
  323,
  2453,
  382,
  785,
  5492,
  572,
  1083,
  50187,
  9761,
  553,
  8713,
  22410,
  18841,
  389,
  1059,
  220,
  16,
  24,
  22,
  16,
  8017,
  353,
  40,
  14695,
  84027,
  1446,
  41569,
  12314,
  892,
  8910,
  4446,
  432,
  311,
  458,
  1496,
  21864,
  10650,
  382,
  27989,
  498,
  1075,
  311,
  1414,
  803,
  911,
  279,
  5492,
  594,
  4004,
  11,
  1181,
  5421,
  11,
  476,
  1181,
  12752,
  25361,
  30,
  151645],
 'generated_tokens': ['Absolutely',
  '!',
  ' "',
  'Bridge',
  ' Over',
  ' Trou',
  'bled',
  ' Water',
  '"',
  ' is',
  ' one',
  ' of',
  ' the',
  ' most',
  ' beloved',
  ' and',
  ' enduring',
  ' songs',
  ' in',
  ' the',
  ' history',
  ' of',
  ' popular',
  ' music',
  ',',
  ' written',
  ' by',
  ' Paul',
  ' Simon',
  ' and',
  ' released',
  ' in',
  ' ',
  '1',
  '9',
  '7',
  '0',
  ' as',
  ' the',
  ' final',
  ' track',
  ' on',
  ' Simon',
  ' &',
  ' Gar',
  'f',
  'unk',
  'el',
  "'s",
  ' *',
  'Bridge',
  ' Over',
  ' Trou',
  'bled',
  ' Water',
  '*',
  ' album',
  '.',
  ' It',
  "'s",
  ' often',
  ' regarded',
  ' as',
  ' one',
  ' of',
  ' the',
  ' greatest',
  ' songs',
  ' of',
  ' all',
  ' time',
  ',',
  ' known',
  ' for',
  ' its',
  ' poetic',
  ' lyrics',
  ',',
  ' emotional',
  ' depth',
  ',',
  ' and',
  ' powerful',
  ' message',
  ' of',
  ' support',
  ' and',
  ' companions',
  'hip',
  '.\n\n',
  'Here',
  ' are',
  ' the',
  ' complete',
  ' lyrics',
  ':\n\n',
  '---\n\n',
  '**',
  'Bridge',
  ' Over',
  ' Trou',
  'bled',
  ' Water',
  '**',
  '  \n',
  '*',
  'by',
  ' Paul',
  ' Simon',
  '*\n\n',
  'There',
  "'s",
  ' a',
  ' bridge',
  ' over',
  ' troubled',
  ' water',
  ',',
  '  \n',
  'I',
  ' heard',
  ' it',
  "'s",
  ' wide',
  ' and',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ',',
  '  \n',
  'I',
  "'m",
  ' trying',
  ' to',
  ' find',
  ' my',
  ' way',
  ' back',
  ' to',
  ' the',
  ' shore',
  ',',
  '  \n',
  'But',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ' and',
  ' I',
  ' can',
  "'t",
  ' see',
  ' for',
  ' sure',
  '.',
  '  \n',
  'So',
  ',',
  ' if',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  ',',
  '  \n',
  'If',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n\n',
  'There',
  "'s",
  ' a',
  ' bridge',
  ' over',
  ' troubled',
  ' water',
  ',',
  '  \n',
  'I',
  ' heard',
  ' it',
  "'s",
  ' wide',
  ' and',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ',',
  '  \n',
  'I',
  "'m",
  ' trying',
  ' to',
  ' find',
  ' my',
  ' way',
  ' back',
  ' to',
  ' the',
  ' shore',
  ',',
  '  \n',
  'But',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ' and',
  ' I',
  ' can',
  "'t",
  ' see',
  ' for',
  ' sure',
  '.',
  '  \n',
  'So',
  ',',
  ' if',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  ',',
  '  \n',
  'If',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n\n',
  'There',
  "'s",
  ' a',
  ' bridge',
  ' over',
  ' troubled',
  ' water',
  ',',
  '  \n',
  'I',
  ' heard',
  ' it',
  "'s",
  ' wide',
  ' and',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ',',
  '  \n',
  'I',
  "'m",
  ' trying',
  ' to',
  ' find',
  ' my',
  ' way',
  ' back',
  ' to',
  ' the',
  ' shore',
  ',',
  '  \n',
  'But',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ' and',
  ' I',
  ' can',
  "'t",
  ' see',
  ' for',
  ' sure',
  '.',
  '  \n',
  'So',
  ',',
  ' if',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  ',',
  '  \n',
  'If',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n\n',
  'There',
  "'s",
  ' a',
  ' bridge',
  ' over',
  ' troubled',
  ' water',
  ',',
  '  \n',
  'I',
  ' heard',
  ' it',
  "'s",
  ' wide',
  ' and',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ',',
  '  \n',
  'I',
  "'m",
  ' trying',
  ' to',
  ' find',
  ' my',
  ' way',
  ' back',
  ' to',
  ' the',
  ' shore',
  ',',
  '  \n',
  'But',
  ' the',
  ' waters',
  ' are',
  ' wide',
  ' and',
  ' I',
  ' can',
  "'t",
  ' see',
  ' for',
  ' sure',
  '.',
  '  \n',
  'So',
  ',',
  ' if',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  ',',
  '  \n',
  'If',
  ' you',
  "'re",
  ' going',
  ' through',
  ' the',
  ' troubled',
  ' waters',
  ',',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n',
  'I',
  ' will',
  ' be',
  ' there',
  ' to',
  ' help',
  ' you',
  '.',
  '  \n\n',
  '---\n\n',
  'This',
  ' song',
  "'s",
  ' enduring',
  ' appeal',
  ' lies',
  ' in',
  ' its',
  ' universal',
  ' message',
  ' of',
  ' support',
  ' and',
  ' solidarity',
  '.',
  ' It',
  "'s",
  ' often',
  ' interpreted',
  ' as',
  ' a',
  ' metaphor',
  ' for',
  ' emotional',
  ' or',
  ' psychological',
  ' struggles',
  ',',
  ' and',
  ' the',
  ' repeated',
  ' chorus',
  ' serves',
  ' as',
  ' a',
  ' comforting',
  ' promise',
  ' of',
  ' presence',
  ' and',
  ' care',
  '.\n\n',
  'The',
  ' song',
  ' was',
  ' also',
  ' famously',
  ' covered',
  ' by',
  ' Are',
  'tha',
  ' Franklin',
  ' on',
  ' her',
  ' ',
  '1',
  '9',
  '7',
  '1',
  ' album',
  ' *',
  'I',
  ' Never',
  ' Loved',
  ' You',
  ' Anyway',
  '*,',
  ' which',
  ' helped',
  ' bring',
  ' it',
  ' to',
  ' an',
  ' even',
  ' wider',
  ' audience',
  '.\n\n',
  'Would',
  ' you',
  ' like',
  ' to',
  ' know',
  ' more',
  ' about',
  ' the',
  ' song',
  "'s",
  ' background',
  ',',
  ' its',
  ' impact',
  ',',
  ' or',
  ' its',
  ' cultural',
  ' significance',
  '?',
  '<|im_end|>'],
 'token_log_probs': [-0.027884379029273987,
  -0.035607870668172836,
  -0.8293450474739075,
  -7.152560215217818e-07,
  0.0,
  0.0,
  0.0,
  0.0,
  -1.1920930376163597e-07,
  -0.01948082074522972,
  -0.001133368699811399,
  0.0,
  -0.006715324241667986,
  -0.00013090037100482732,
  -2.162611961364746,
  -0.039414599537849426,
  -0.0065221828408539295,
  -9.084160410566255e-05,
  -0.0018105794442817569,
  -0.04441274330019951,
  -0.005607022903859615,
  0.0,
  -0.008067398332059383,
  0.0,
  -1.9411752223968506,
  -0.006044679321348667,
  -0.006715324241667986,
  -0.0010824098717421293,
  0.0,
  -0.004746478050947189,
  -0.19267156720161438,
  -0.4031718373298645,
  0.0,
  0.0,
  0.0,
  -9.059946933120955e-06,
  0.0,
  -0.0023406697437167168,
  -0.5304735898971558,
  -0.9384106397628784,
  -0.00046550139086320996,
  -0.1610569953918457,
  -0.0028693077620118856,
  0.0,
  0.0,
  0.0,
  0.0,
  -5.960482212685747e-06,
  -0.013669934123754501,
  -0.35938116908073425,
  -0.27123159170150757,
  -0.002755560679361224,
  -1.1920930376163597e-07,
  0.0,
  0.0,
  0.0,
  -1.1920930376163597e-07,
  -0.0007939509232528508,
  -0.09133021533489227,
  -0.055668748915195465,
  -0.743881106376648,
  -0.22539569437503815,
  -3.576279254957626e-07,
  -0.22361326217651367,
  0.0,
  -3.325994475744665e-05,
  -0.016745034605264664,
  -0.0031996839679777622,
  -0.055844392627477646,
  -0.0016134873731061816,
  0.0,
  -0.01068408228456974,
  -1.3978489637374878,
  -1.2993897144042421e-05,
  -2.3841860752327193e-07,
  -0.6097071170806885,
  -0.0037764599546790123,
  -0.0023052420001477003,
  -0.3034049868583679,
  -0.00013328486238606274,
  0.0,
  0.0,
  -1.9499043226242065,
  -0.003960993140935898,
  -4.94730775244534e-05,
  -0.05796784907579422,
  -0.0001511688024038449,
  -1.9683763980865479,
  0.0,
  -0.02684231661260128,
  -2.4915052563301288e-05,
  -0.05616134777665138,
  -4.529963462118758e-06,
  -0.1560022532939911,
  -1.1920930376163597e-07,
  -0.8959878087043762,
  -0.0013597310753539205,
  -0.00019009728566743433,
  -0.766232967376709,
  0.0,
  0.0,
  0.0,
  0.0,
  -0.0006706579006277025,
  0.0,
  -0.001161235966719687,
  -0.020675865933299065,
  -0.027727734297513962,
  0.0,
  -1.4019684791564941,
  -2.216066837310791,
  -0.055941902101039886,
  -5.006802894058637e-06,
  -9.847171895671636e-05,
  -0.002102199010550976,
  -2.5033982637978625e-06,
  -1.1920930376163597e-07,
  -0.15501736104488373,
  -0.013669934123754501,
  -1.1920930376163597e-07,
  -0.7178449034690857,
  -0.46284574270248413,
  -0.656440258026123,
  -0.043741997331380844,
  -7.74863383412594e-06,
  -0.5931972861289978,
  -0.037586748600006104,
  -0.0019351477967575192,
  -0.007188285235315561,
  -0.07896390557289124,
  0.0,
  -0.004018682055175304,
  -1.1129419803619385,
  -0.0021452652290463448,
  -3.576279254957626e-07,
  -0.06141611188650131,
  -0.007754331920295954,
  -2.7418175250204513e-06,
  -0.358347088098526,
  -0.0003882804303430021,
  -1.053563117980957,
  -1.3819962739944458,
  -0.0035665978211909533,
  0.0,
  -0.24649088084697723,
  -1.0198602676391602,
  -0.7459961175918579,
  -0.18204481899738312,
  -0.06894101202487946,
  -0.2588433623313904,
  -1.1282637119293213,
  -2.5837039947509766,
  -0.0011291319970041513,
  -0.06683289259672165,
  -1.9411476850509644,
  -0.01835840940475464,
  -0.5402351021766663,
  -0.1550169438123703,
  -3.6469476222991943,
  -2.9959983825683594,
  -0.9341357946395874,
  -4.0293551137438044e-05,
  -0.03856858238577843,
  -0.2543046474456787,
  -4.768372718899627e-07,
  -1.8209571838378906,
  -1.9732385873794556,
  -2.253788948059082,
  -0.0002893031924031675,
  -5.960466182841628e-07,
  -0.11624836921691895,
  -2.7526676654815674,
  -0.0009793068747967482,
  -0.056075792759656906,
  -0.03096502274274826,
  -0.03882985562086105,
  -6.938221486052498e-05,
  -0.014216930605471134,
  -0.0813179686665535,
  -1.1814265251159668,
  -3.671713420771994e-05,
  -9.32260081754066e-05,
  -2.8729851692332886e-05,
  -3.576279254957626e-07,
  -0.00011528202594490722,
  -1.3113030945532955e-06,
  -0.00018938188441097736,
  -5.5910721130203456e-05,
  0.0,
  -0.0031999233178794384,
  -0.00394052779302001,
  -5.960466182841628e-07,
  -0.00032692530658096075,
  -0.00047265729517675936,
  -0.0003243018581997603,
  -2.3841860752327193e-07,
  -0.36559033393859863,
  -0.15502014756202698,
  -1.5337759256362915,
  -0.0673784613609314,
  -3.647870835266076e-05,
  -0.003943998366594315,
  -0.00022813299437984824,
  -0.0002269406249979511,
  0.0,
  -0.6471964716911316,
  -1.2361050844192505,
  -0.2710133492946625,
  -0.0004345526685938239,
  -8.344653679159819e-07,
  -0.004769954364746809,
  -1.120573597290786e-05,
  -2.3841860752327193e-07,
  -1.7881409348774469e-06,
  -0.0001923626841744408,
  0.0,
  -0.02832043170928955,
  -7.891966379247606e-05,
  -0.00037057112785987556,
  -4.2439409298822284e-05,
  -0.0018193572759628296,
  -0.0019466738449409604,
  -2.6464813345228322e-05,
  -3.552499765646644e-05,
  0.0,
  -1.0609683158691041e-05,
  -0.00039281215867958963,
  0.0,
  -0.02118573524057865,
  -0.0028341005090624094,
  -7.725060277152807e-05,
  -3.576279254957626e-07,
  -1.1920930376163597e-07,
  -7.033372639853042e-06,
  0.0,
  -9.059946933120955e-06,
  -3.576279254957626e-07,